In [7]:
import numpy as np
A = np.zeros(4)
print(A)

[0. 0. 0. 0.]


In [1]:
#tích ma trận:
import numpy as np 

#Nhập kích thước ma trận
m= int(input("Nhập số hàng của ma trận A: "))
n= int(input("Nhập số cột của ma trận A (cũng là số hàng của B): "))
p= int(input("Nhập số cột của ma trận B: "))

#Nhập ma trận A (m x n)
print ("\nNhập ma trận A:")
A=np.array([[float(input(f"A[{i}][{j}]: ")) for j in range(n)] for i in range(m)])
print (A)
#Nhập ma trận B (n x p)
print("\nNhập ma trận B:")
B= np.array([[float(input(f"B[{i}][{j}]: ")) for j in range(p)] for i in range(n)])
print(B)
#Nhân hai ma trận
tich= np.dot(A, B) #hoặc dùng A @ B

print ("\nMa trận tích A x B:")
print(tich)



Nhập ma trận A:
[[1. 2.]
 [3. 4.]
 [2. 3.]]

Nhập ma trận B:
[[2. 3. 1.]
 [3. 1. 4.]]

Ma trận tích A x B:
[[ 8.  5.  9.]
 [18. 13. 19.]
 [13.  9. 14.]]


In [ ]:
#Tính Det(A) = hàm laplace
import numpy as np
from sympy import Matrix

def determinant_laplace(matrix):
    """
    Tính định thức ma trận bằng phương pháp lapace 
    :param matrix: Ma trận vuông (numpy hoặc list lồng nhau)
    :return: Gía trị định thức của ma trận
    """
    matrix = np.array(matrix)
    n=matrix.shape[0]

    #Điều kiện dừng: Ma trận 1x1
    if n == 1:
        return matrix[0, 0]
    #Điều kiện dừng: Ma trận 2x2
    if n == 2:
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]
    
    det=0
    for j in range(n): #Duyệt theo từng phần tử của hàng đầu tiên
        sub_matrix = np.delete(np.delete(matrix, 0, axis=0), j, axis=1) #ma trận con
        cofactor= (-1) ** j * matrix[0, j] * determinant_laplace(sub_matrix)
        det += cofactor

    return det

#Nhập ma trận từ user
def input_matrix():
    n=int(input("Nhập kích thước ma trận vuông A (n x n): "))
    matrix = []
    print("Nhập từng dòng của ma trận, cách nhau bởi dấu cách:")
    for i in range(n):
        row = list(map(float, input(f"Dòng {i+1}: ").split()))
        matrix.append(row)
    return np.array(matrix)

#chạy chương trình
matrix = input_matrix()
det = determinant_laplace(matrix)
print ("Định thức của ma trận là: det(A) = ",det,)
print ("det(A) khác 0 suy ra ma trận khả nghịch")
if det ==0:
        print("\nMa trận không khả nghịch vì định thức = 0.")
else:
        #tính nghịch đảo
        A_inv= np.linalg.inv(matrix)
        print("\nMa trận nghịch đảo là:")
        print(A_inv)

    

Nhập từng dòng của ma trận, cách nhau bởi dấu cách:
Định thức của ma trận là: det(A) =  2.0
det(A) khác 0 suy ra ma trận khả nghịch

Ma trận nghịch đảo là:
[[-1.5 -1.5  2. ]
 [ 1.   1.  -1. ]
 [-0.5  0.5 -0. ]]


In [ ]:
import numpy as np

#nhập kích thước ma trận vuông
n=int(input("Nhập kích thước ma trận vuông (n): "))

#Nhập ma trận A
print("\nNhập ma trận A:")
A= np. array([[float(input(f"A[{i}][{j}]: ")) for j in range(n)] for i in range(n)])

#kiểm tra định thức
det_A=np.linalg.det(A)
if det_A ==0:
    print("\nMa trận không khả nghịch vì định thức = 0.")
else:
    #tính nghịch đảo
    A_inv= np.linalg.inv(A)
    print("\nMa trận nghịch đảo là:")
    print(A_inv)

    #kiểm tra: A*A^-1 có ra ma trận đơn vị không?
    print ("\n Kiểm tra A*A^-1:")
    print(np.round(np.dot(A, A_inv), 5))  #làm tròn


Nhập ma trận A:

Ma trận nghịch đảo là:
[[ 0.8  1.2 -0.6  0.8]
 [-1.4 -6.6  3.8 -5.4]
 [ 0.6  0.4 -0.2  0.6]
 [ 0.4  1.6 -0.8  1.4]]

 Kiểm tra A*A^-1:
[[ 1.  0. -0. -0.]
 [-0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


In [ ]:
#hangmatran
import numpy as np
def input_matrix():
    n, m= map(int, input("Nhập số hàng và số cột của ma trận (cách nhau bởi dấu cách): ").split())
    print("Nhập từng dòng của ma trận, cách nhau bởi dấu cach:")
    #khởi tạo ma trận rỗng 
    A = np.zeros((m,n))
    matrix = []
    for i in range(n):
        row = list(map(float, input(f"Dong {i+1}: ").split()))
        matrix.append(row)
    return np.array(matrix)

# Nhập ma trận và tính hạng
A = input_matrix()
rank = np.linalg.matrix_rank(A)
print ("Ma trận A:\n",A)
print ("Hạng của ma trận A:", rank)

Nhập từng dòng của ma trận, cách nhau bởi dấu cach:
Ma trận A:
 [[1. 2. 3. 1. 2.]
 [2. 3. 1. 2. 3.]
 [3. 1. 2. 3. 1.]
 [3. 5. 4. 3. 5.]]
Hạng của ma trận: 3


In [10]:
#Ma trận
import numpy as np
#nhap kich thuoc ma tran
m=int(input("Nhập số hàng (m): "))
n=int(input("Nhập số cột (n): "))

#khởi tạo ma trận rỗng 
A = np.zeros((m,n))

#nhập từng phần tử
for i in range(m):
    for j in range(n):
        A[i,j]=float(input(f"Nhập phần tử A[{i+1}][{j+1}]: "))

print("Ma trận A:")
print(A)        



Ma trận A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [2]:
#Ma trận chuyển vị liên hợp
import numpy as np

#kích thước ma trận
m=int(input("Nhập số hàng (m): "))
n=int(input("Nhập số cột (n): "))

#dữ liệu ma trận số phức
A=[]
print(f"Nhập ma trận {m}x{n},mỗi hàng nhập số phức(vd: 1+2j, 3+3j): ")
for i in range(m):
    row = list(map(complex, input(f"Hàng {i+1}: ").split()))
    A.append(row)

#chuyển thành mảng numpy
A=np.array(A, dtype=np.complex128)

#Tính ma trận chuyển vị liên hợp
A_H=A.conj().T

print("Ma trận A: ")
print(A)
print("\nMa trận chuyển vị liên hợp A^H: ")
print (A_H)

Nhập ma trận 3x2,mỗi hàng nhập số phức(vd: 1+2j, 3+3j): 
Ma trận A: 
[[-1.+2.j  0.+0.j]
 [ 3.+0.j  6.-3.j]
 [ 4.+1.j  9.-4.j]]

Ma trận chuyển vị liên hợp A^H: 
[[-1.-2.j  3.-0.j  4.-1.j]
 [ 0.-0.j  6.+3.j  9.+4.j]]


In [14]:
import numpy as np

#kích thước ma trận vuông(nxn)
n = int(input("Nhập kích thước ma trận vuông (n): "))

#Nhập từng phần tử từ bàn phím
A=[]
print(f"Nhập ma trận {n}x{n}, mỗi hàng nhập các số cách nhau bởi dấu cách:")
for i in range(n):
    row = list(map(float, input(f"Hàng {i+1}: ").split()))
    A.append(row)

#Chuyển thành mảng numpy
A= np.array(A)

print("\nMa trận vuông a: ")
print(A)

Nhập ma trận 2x2, mỗi hàng nhập các số cách nhau bởi dấu cách:

Ma trận vuông a: 
[[1. 2.]
 [3. 4.]]


In [5]:
#MA TRẬN BẬC THANG
import numpy as np

def row_echelon_form(A):     #bac thang
    A=A.astype(float) #chuyển về số thực để tránh lỗi chia
    rows, cols = A.shape
    pivot_row=0

    for col in range(cols):
        #Tìm hàng có phần tử lớn nhất trong cột hiện tại ( tránh chia cho 0)
        max_row = pivot_row+ np.argmax(np.abs(A[pivot_row:, col]))

        #Nếu phần tử lớn nhất là 0 thì bỏ qua cột này
        if A[max_row, col]==0:
            continue
        #Đổi hàng hiện tại với hàng có phần tử lớn nhất
        A[[pivot_row, max_row]]= A[[max_row, pivot_row]]

        #biến đổi hàng sao cho phần tử trụ bằng 1
        A[pivot_row]=A[pivot_row]/A[pivot_row, col]

        #Khử các phần tử bên dưới tử trụ
        for row in range(pivot_row+1, rows):
            A[row]-= A[row, col] * A[pivot_row]

        pivot_row += 1
        if pivot_row == rows:
            break

    return A

#Nhập ma trận
m=int(input("Nhập số hàng (m): "))
n=int(input("Nhập số cột (n): "))

A=[]
print(f"Nhập ma trận {m}x{n}, mỗi hàng cách nhau bởi dấu cách:")
for i in range(m):
    row=list(map(float, input(f"Hàng {i+1}: ").split()))
    A.append(row)

A=np.array(A)
A_ref= row_echelon_form(A.copy())

print("\nMa trận bậc thang (Row Echelon Form): ")
print(A_ref)

Nhập ma trận 4x4, mỗi hàng cách nhau bởi dấu cách:

Ma trận bậc thang (Row Echelon Form): 
[[ 1.  2.  3.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1. -0.]
 [ 0.  0.  0.  0.]]


In [ ]:
#Tính Det(A)
import numpy as np
from sympy import Matrix

def determinant_laplace(matrix):
    """
    Tính định thức ma trận bằng phương pháp lapace 
    :param matrix: Ma trận vuông (numpy hoặc list lồng nhau)
    :return: Gía trị định thức của ma trận
    """
    matrix = np.array(matrix)
    n=matrix.shape[0]

    #Điều kiện dừng: Ma trận 1x1
    if n == 1:
        return matrix[0, 0]
    #Điều kiện dừng: Ma trận 2x2
    if n == 2:
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]
    
    det=0
    for j in range(n): #Duyệt theo từng phần tử của hàng đầu tiên
        sub_matrix = np.delete(np.delete(matrix, 0, axis=0), j, axis=1) #ma trận con
        cofactor= (-1) ** j * matrix[0, j] * determinant_laplace(sub_matrix)
        det += cofactor

    return det

#Nhập ma trận từ user
def input_matrix():
    n=int(input("Nhập kích thước ma trận vuông A (n x n): "))
    matrix = []
    print("Nhập từng dòng của ma trận, cách nhau bởi dấu cách:")
    for i in range(n):
        row = list(map(float, input(f"Dòng {i+1}: ").split()))
        matrix.append(row)
    return np.array(matrix)

#chạy chương trình
matrix = input_matrix()
det = determinant_laplace(matrix)
print ("Định thức của ma trận là: det(A)= ",det)

Nhập từng dòng của ma trận, cách nhau bởi dấu cách:
Định thức của ma trận là:  2.0


In [16]:
import numpy as np

#nhập kích thước ma trận vuông
n=int(input("Nhập kích thước ma trận vuông (n): "))

#Nhập ma trận A
print("\nNhập ma trận A:")
A= np. array([[float(input(f"A[{i}][{j}]: ")) for j in range(n)] for i in range(n)])

#kiểm tra định thức
det_A=np.linalg.det(A)
if det_A ==0:
    print("\nMa trận không khả nghịch vì định thức = 0.")
else:
    #tính nghịch đảo
    A_inv= np.linalg.inv(A)
    print("\nMa trận nghịch đảo là:")
    print(A_inv)



Nhập ma trận A:

Ma trận nghịch đảo là:
[[-1.5 -1.5  2. ]
 [ 1.   1.  -1. ]
 [-0.5  0.5 -0. ]]


In [ ]:
import numpy as np

def gauss_jordan_inverse (matrix):
    """
    Tìm ma trận nghịch đảo bằng pp Gauss-Jordan

    :param matrix: Ma trận vuông (numpy array)
    :return: Ma trận nghịch đảo nếu tồn tại, ngược lại báo lỗi
    """

    matrix = np.array(matrix, dtype=float)
    n = matrix.shape[0]

    #tạo ma trận mở rộng [ A | I ]
    augmented_matrix= np.hstack((matrix, np.eye(n)))

    #Ap dụng phép biển đổi hàng
    for i in range(n):
        #Tìm phần tử chính (pivot)
        pivot = augmented_matrix[i, i]
        if abs(pivot) < 1e-10:  #ktra nếu pivot quá nhỏ hoặc = 0
            raise ValueError("Ma trận không khả nghịch!")
        
        #Chia hàng i cho pivot để pivot trở thành 1
        augmented_matrix[i] = augmented_matrix[i] / pivot

        #Dùng hàng i để khử các phần tử trong cột
        for j in range(n):
            if i !=j:
                factor = augmented_matrix[j, i]
                augmented_matrix[j] -= factor * augmented_matrix[i]

    #Phần bên phải là ma trận nghịch đảo
    inverse_matrix=augmented_matrix[:, n:]
    return inverse_matrix

#Nhập ma trận từ người dùng
def input_matrix():
    n= int(input("Nhập kích thước ma trận vuông n x n: "))
    
    #khởi tạo ma trận rỗng 
    matrix = []
    print("Nhập từng dòng của ma trận, cách nhau bởi dấu cách: ")
    for i in range(n):
        row = list(map(float, input(f"Dòng {i+1}: ").split()))
        matrix.append(row)
    return np.array(matrix)

#run
try:
    A= input_matrix()
    A_inv = gauss_jordan_inverse(A)
    print("Ma trận nghịch đảo của A là:\n", A_inv)
except ValueError as error:
    print(error)




Nhập từng dòng của ma trận, cách nhau bởi dấu cách: 
Ma trận nghịch đảo của A là:
 [[-1.33333333 -2.          1.         -1.33333333]
 [ 2.33333333 -1.          1.         -1.66666667]
 [-1.         -2.          1.         -1.        ]
 [-0.66666667  0.          0.          0.33333333]]
