In [ ]:
#vector co ban
import numpy as np

def input_vector(dim, index):
    """nhập một vector có độ dài dim"""
    print(f"Nhập vector {index} có {dim} phần tử:")
    return np.array([float(input(f"Phần tử {i+1}: ")) for i in range(dim)])

def is_linearly_independent(vectors):
    """Ktra tập vector có độc lập tuyến tính không"""
    matrix = np.column_stack(vectors)
    rank= np.linalg.matrix_rank(matrix)
    return rank == len(vectors)

#1 Nhập số chiều không gian vector
dim = int(input("Nhập số chiều của không gian vector (n): "))

#2 Nhập số lượng vector cần kiểm tra
num_vectors = int(input("Nhập số lượng vector: "))

#3 Nhập danh sách vector
vectors = [input_vector(dim, i+1) for i in range(num_vectors)]

#Hiển thị các vector đã nhập
print("\nCác vector đã nhập:")
for i, v in enumerate(vectors, 1):   #locate
    print(f"v{i} = {v}")

#4 Thực hiện phép cộng vector ( nếu có ít nhất 2 vector)
if num_vectors > 1:
    sum_vector = sum(vectors)
    print("\nTổng của các vector:", sum_vector)

#5 Thực hiện phép nhân vô hướng
alpha = float(input("\nNhập một số vô hướng để nhân với vector đầu tiên: "))
scaled_vector = alpha * vectors[0]
print(f"Nhân vector v1 với {alpha}:", scaled_vector)

#6 Ktra phần tử trung lập (vector 0)
zero_vector = np.zeros(dim)
print("\nVector không (trung lập phép cộng):", zero_vector)

#7 Tìm phần tử đối của từng vector
opposite_vectors = [-v for v in vectors]
print("\nPhần tử đối của từng vector:")
for i, v in enumerate(opposite_vectors, 1):
    print(f"Phần tử đối của v{i}: {v}")

#8 Ktra độc lập tuyến tính
if is_linearly_independent(vectors):
    print("\nCác vector là độc lập tuyến tính.")
else:
    print("\nCác vector phụ thuộc tuyến tính.")

#9 Xác định số chiều của không gian vector sinh ra
basis = np.column_stack(vectors)
dimension = np.linalg.matrix_rank(basis)
print("Số chiều của không gian vector là:", dimension)


Nhập vector 1 có 3 phần tử:
Nhập vector 2 có 3 phần tử:

Các vector đã nhập:
v1 = [1. 2. 3.]
v2 = [3. 4. 1.]

Tổng của các vector: [4. 6. 4.]
Nhân vector v1 với 2.0: [2. 4. 6.]

Vector không (trung lập phép cộng): [0. 0. 0.]

Phần tử đối của từng vector:
Phần tử đối của v1: [-1. -2. -3.]
Phần tử đối của v2: [-3. -4. -1.]

Các vector là độc lập tuyến tính.
Số chiều của không gian vector là: 2


In [3]:
#CƠ SỞ 
import numpy as np

def is_basis(vectors):
    """
    Kiểm tra xem tập vectors có phải là một cơ sở của KGVT 
    """

    #Chuyển danh sách vector thành ma trận
    matrix = np.array(vectors).T

    #Lấy số vector và số chiều KGVT
    num_vectors, dimension = matrix.shape[1], matrix.shape[0]

    #Điều kiện: số vector phải bằng số chiều KGVT
    if num_vectors != dimension:
        return False, "Số vector không bằng số chiều của không gian vector => Không phải là cơ sở."

    #Kiểm tra độc lập tuyến tính: Rank của ma trận phải = số chiều KGVT
    rank = np.linalg.matrix_rank(matrix)
    if rank < dimension:
        return False, "Tập vector phụ thuộc tuyến tính => không phải là cơ sở."
    return True, "Ta có:\n-Phần tử của tập vector = số chiều KGVT.\n-Tập vector độc lập tuyến tính. \n=> là cơ sở của KGVT."

#Nhập số chiều của không gian
try:
    n= int(input("Nhập số chiều của KGVT (n): "))
    if n <= 0:
        raise ValueError
except ValueError:
    print("Lỗi: n phải là số nguyên dương")
    exit()

#Nhập các vector từ bàn phím
vectors = []
print(f"Nhập {n} vector, mỗi vector gồm {n} phần tử ( cách nhay bởi dấu cách):")
for i in range(n):
    try:
        vector = list(map(float, input(f"Vector {i+1}: ").split()))
        if len(vector) != n:
               raise ValueError
        vectors.append(vector)
    except ValueError:
        print("Lỗi: Mỗi vector phải có đúng n phần tử!")
        exit()
print(vectors)

#Ktra xem tập vector có là cơ sở không
is_basis_result, message = is_basis(vectors)
print(message)





Nhập 4 vector, mỗi vector gồm 4 phần tử ( cách nhay bởi dấu cách):
[[1.0, 1.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 1.0, 1.0], [1.0, 0.0, 0.0, 0.0]]
Ta có:
-Phần tử của tập vector = số chiều KGVT.
-Tập vector độc lập tuyến tính. 
=> là cơ sở của KGVT.


In [ ]:
#FIND DIMENSION
import numpy as np

def find_vector_space_dimension(vectors):
    """
    Xác định số chiều KGVT dựa vào Rank của ma trận chứa các vector
    """

    matrix = np.array(vectors)   #Chuyển danh sách vector thành ma trận
    rank = np.linalg.matrix_rank(matrix)    #Tính hạng ma trận
    return rank

#Nhập số vector
try:
    n= int(input("Nhập số vector: "))
    
    
    vector = []

    #Nhập từng vector
    for i in range(n):
        vec = list(map(float, input(f"Nhập vector {i+1} (các phần tử cách nhau bởi dấu cách): ").split()))
        vectors.append(vec)
    
    #Xác định số chiều của không gian vector
    dim = find_vector_space_dimension(vectors)
    print(f"Số chiều của không gian vector: {dim}")

except ValueError:
    print("Lỗi! Hãy nhập số nguyên hợp lẹ và các phần tử số thực cách nhau bởi dấu cách!")
    

Số chiều của không gian vector: 3


In [1]:
#Trực chuẩn hóa Gram-Schmidt

import numpy as np

def gram_schmidt(V):
    """
    trực chuẩn hóa GRAM-SCHMIDT trên tập hợp vector V.

    Args:
        V: Ma trận numpy (mxn), mỗi cột là một vector đầu vào.

    Returns:
        U: Ma trận chứa các vector trực chuẩn.    
    """
    V = np.array(V, dtype=np.float64)
    m, n = V.shape
    U = []

    for i in range(n):
        u_i = V[:, i]  #lay vector hien tai
        for u_j in U:  #Loai bo thanh phan chieu len cac vector truoc do
            proj = (np.dot(u_j, u_i) / np.dot(u_j, u_j)) * u_j
            u_i = u_i - proj
    
        norm_u_i = np.linalg.norm(u_i)  #chuẩn của vector
        if norm_u_i > 1e-10:  #Kiểm tra nếu vector không bị triệt tiêu hoàn toàn
            U.append(u_i/norm_u_i) #chuẩn hóa vector

    return np.array(U).T  #Chuyển dạng ma trận để mỗi cột là một vector trực chuẩn

#Nhập số vector và số chiều từ bàn phím
num_vectors = int(input("Nhập số lượng vector: "))
vector_dim = int(input("Nhập số chiều của vector: "))

#Nhập các vector từ bàn phím
vectors = []
print (f"Nhập từng vector (mỗi phần tử cách nhau bằng dấu cách):")
for i in range(num_vectors):
    vector = list(map(float, input(f"Vector {i+1}: ").split()))
    if len(vector) != vector_dim:
        print("Lỗi: Số phần tử không đúng, vui lòng nhập lại!")
        exit()
    vectors.append(vector)

#Chuyển đổi sang numpy array và thực hiện Gram-Schmidt
V = np.array(vectors).T  #chuyển ma trận để mỗi cột là một vector
U = gram_schmidt(V)

#OUTPUT
print("\nCác vector trực chuẩn hóa:")
print(U.T)    # chuyển lại dạng vector ban đầu.

Nhập từng vector (mỗi phần tử cách nhau bằng dấu cách):

Các vector trực chuẩn hóa:
[[ 0.57735027 -0.57735027  0.57735027]
 [-0.40824829  0.40824829  0.81649658]
 [ 0.70710678  0.70710678  0.        ]]


In [14]:
import numpy as np

def is_linear_mapping(A):
    """ Kiểm tra ảnh của ma trận có phải là ánh xạ tuyến tính không. """
    return True  # Mọi ánh xạ biểu diễn bởi ma trận đều là tuyến tính

def find_image(A):
    """ Tìm ảnh của ánh xạ tuyến tính (Im(f)) (tức là không gian cột của ma trận A). """
    U, S, Vt = np.linalg.svd(A)  # Phân rã SVD để tìm các vector độc lập
    rank = np.linalg.matrix_rank(A)  # Hạng của A
    image_basis = U[:,:rank]  # Cơ sở của không gian cột (Imf)
    return image_basis

def find_kernel(A):
    """ Tìm hạt nhân của ánh xạ tuyến tính (Ker(f)), tức là tập nghiệm của Ax = 0. """
    m,n = A.shape
    U, S, Vt = np.linalg.svd(A)  # Phân rã SVD để tìm không gian null
    null_space = Vt[len(S):].T  # Vector tương ứng với giá trị suy biến
    return null_space

# Nhập kích thước của ma trận ánh xạ tuyến tính
m = int(input("Nhập số hàng của ma trận ánh xạ: "))  # Số chiều đích
n = int(input("Nhập số cột của ma trận ánh xạ: "))  # Số chiều miền xác định

# Nhập ma trận ánh xạ tuyến tính
print(f"Nhập ma trận phản ánh tuyến tính {m}x{n} (mỗi hàng nhập trên 1 dòng, các ptử cách nhau dấu cách):")
A = np.array([list(map(float, input().split())) for _ in range(m)])

# Kiểm tra ánh xạ có phải tuyến tính không
if is_linear_mapping(A):
    print("Ánh xạ f là tuyến tính.")

# Tìm ảnh của f (Im(f))

image = find_image(A)
print("Ảnh của f (Im(f)):")
print(image)

# Tìm hạt nhân của f (Ker(f))
Kernel = find_kernel(A)
print("Hạt nhân của f (Ker(f)):")
print(Kernel if Kernel.size > 0 else "(không có vector nào)")
# tính hạng và số khuyết
# Tính nullity
rank = np.linalg.matrix_rank(A)
nullity = A.shape[1] - rank  # Số khuyết = số biến - hạng
print(f"\nhạng của f (rank): {rank}")
print(f" Số khuyết của f (nullity): {nullity}")

# Nhập vector cần ánh xạ
print(f"Nhập vector đầu vào để ánh xạ (kích thước phải là {n}x1):")
vector = np.array(list(map(float, input().split()))).reshape(n, 1)

# Kiểm tra kích thước hợp lệ
if vector.shape[0] != n:
    print("\nLỗi: Kích thước vector đầu vào không hợp lệ với miền xác định!")
else:
    # Tính ảnh của vector
    result = A @ vector #Tính f(vector) = A * vector
    print("\nKết quả ảnh xạ của vector:")
    print(result)

Nhập ma trận phản ánh tuyến tính 3x2 (mỗi hàng nhập trên 1 dòng, các ptử cách nhau dấu cách):
Ánh xạ f là tuyến tính.
Ảnh của f (Im(f)):
[[-8.16496581e-01  1.85577521e-16]
 [-4.08248290e-01 -7.07106781e-01]
 [-4.08248290e-01  7.07106781e-01]]
Hạt nhân của f (Ker(f)):
(không có vector nào)

hạng của f (rank): 2
 Số khuyết của f (nullity): 0
Nhập vector đầu vào để ánh xạ (kích thước phải là 2x1):

Kết quả ảnh xạ của vector:
[[2.]
 [1.]
 [1.]]
